name: habitly
description: Habitly mobile app - Gamification module
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  get_it: ^7.6.4

  # Network
  dio: ^5.4.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  fl_chart: ^0.65.0

  intl: ^0.19.0
  dartz: ^0.10.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

  mockito: ^5.4.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
